'use client';
import Link from 'next/link';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUp, ChevronRight, Mail, Menu, X } from 'lucide-react';
import { useEffect, useState } from 'react';

const links=[['/','Home'],['/contact','Contact Us'],['/about','About Us'],['/services','Our Services'],['/careers','Careers'],['/faq','FAQ']] as const;
export function Logo(){return <Link className="logo" href="/"><span className="mark">G</span><span>GRANITE<small>OILFIELD SERVICES</small></span></Link>}
export function Navigation(){const [open,setOpen]=useState(false);const [loading,setLoading]=useState(true);const [showTop,setShowTop]=useState(false);useEffect(()=>{const key=(event:KeyboardEvent)=>event.key==='Escape'&&setOpen(false);const onScroll=()=>setShowTop(window.scrollY>450);const timer=window.setTimeout(()=>setLoading(false),650);window.addEventListener('keydown',key);window.addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>{window.removeEventListener('keydown',key);window.removeEventListener('scroll',onScroll);window.clearTimeout(timer)}},[]);return <><AnimatePresence>{loading&&<motion.div className="pagePreloader" initial={{opacity:1}} exit={{opacity:0}} transition={{duration:.4}} aria-label="Loading page"><div><span className="preloaderMark">G</span><strong>GRANITE</strong><i/></div></motion.div>}</AnimatePresence><header><Logo/><button className="menuButton" onClick={()=>setOpen(true)} aria-label="Open navigation menu"><span>MENU</span><Menu size={29}/></button></header><AnimatePresence>{open&&<><motion.button aria-label="Close navigation menu" className="scrim" onClick={()=>setOpen(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside className="drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'tween',ease:[.22,1,.36,1],duration:.45}} aria-label="Navigation"><button className="drawerClose" onClick={()=>setOpen(false)} aria-label="Close navigation menu"><X/></button><Logo/><nav>{links.map(([href,label],i)=><motion.div key={href} initial={{opacity:0,x:22}} animate={{opacity:1,x:0}} transition={{delay:.12+i*.05}}><Link href={href} onClick={()=>setOpen(false)}>{label}<ChevronRight size={18}/></Link>{label==='Our Services'&&<div className="subnav">{[['drilling','Drilling'],['completions','Completions'],['frac','Frac Monitoring'],['plugging','Well Plugging']].map(([id,title])=><Link key={id} href={`/services#${id}`} onClick={()=>setOpen(false)}>{title}</Link>)}</div>}</motion.div>)}</nav><p>DEPENDABLE PEOPLE. RESPONSIVE SERVICE.</p></motion.aside></>}</AnimatePresence><a className="emailWidget" href="mailto:info@graniteoilfieldsinc.com?subject=Granite%20Oilfield%20Services%20Enquiry" title="Email Granite Oilfield Services" aria-label="Email Granite Oilfield Services"><Mail size={22}/><span>Email us</span></a><AnimatePresence>{showTop&&<motion.button className="scrollTop" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="Scroll to top" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:12}}><ArrowUp size={20}/></motion.button>}</AnimatePresence></>}
